# Generated by Django 4.0.6 on 2023-03-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='rating',
            new_name='user_rating',
        ),
    ]
