# Generated by Django 4.0.6 on 2023-04-09 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0008_rename_favorite_userrating_user_favorite'),
        ('user_favorites', '0002_rename_rating_userfavorite_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='user_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_ratings.userrating'),
        ),
    ]
