# Generated by Django 4.0.6 on 2023-03-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_userrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
