# Generated by Django 4.0.6 on 2023-03-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
        ),
    ]
