# Generated by Django 4.0.6 on 2023-03-21 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_page_average_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
