# Generated by Django 4.2 on 2023-04-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_page_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
    ]
