# Generated by Django 4.2 on 2023-04-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_page_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-pk']},
        ),
    ]
