# Generated by Django 4.0.6 on 2023-03-21 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0002_userrating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
