# Generated by Django 4.0.6 on 2023-03-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_favorites', '0001_initial'),
        ('user_ratings', '0004_alter_userrating_options_userrating_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_favorites.userfavorite'),
        ),
    ]
