# Generated by Django 4.0.6 on 2023-03-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0005_alter_userrating_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='rating',
            new_name='user_rating',
        ),
    ]
