# Generated by Django 4.0.6 on 2023-03-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0007_rename_user_rating_userrating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='favorite',
            new_name='user_favorite',
        ),
    ]
