# Generated by Django 4.0.6 on 2023-04-09 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_favorites', '0003_alter_userfavorite_user_rating'),
        ('user_ratings', '0008_rename_favorite_userrating_user_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='user_favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_favorites.userfavorite'),
        ),
    ]
